# frozen_string_literal: true

source 'https://rubygems.org/'

group :lint do
  gem 'brakeman'
  gem 'bundler-audit'
  gem 'coveralls'
  gem 'fasterer'
  gem 'foodcritic'
  gem 'mdl'
  gem 'overcommit'
  gem 'rubocop'
  gem 'travis'
end

group :chef do
  gem 'berkshelf'
  gem 'chef', '11.10'
  gem 'chef-zero'
  gem 'chefspec'
  gem 'kitchen-docker'
  gem 'kitchen-vagrant'
  gem 'rspec'
  gem 'test-kitchen'
end
